sudo: required
services:
    - docker

before_install:
    - docker build -t tomasoares/docker-react -f Dockerfile.dev .
    
script:
    - docker run tomasoares/docker-react npm run test -- --coverage